=== MRCIEU/llm-data-extraction/data/assets/data-schema/llama3-2/results.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Results",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "exposure": { "type": "string" },
      "outcome": { "type": "string" },
      "beta": { "type": ["number", "null", "string"] },
      "units": { "type": ["string", "null"] },
      "odds ratio": { "type": ["number", "null", "string"] },
      "hazard ratio": { "type": ["number", "null", "string"] },
      "95% CI": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": ["array", "null"],
            "items": { "type": ["number", "null"] },
            "minItems": 2,
            "maxItems": 2
          }
        ]
      },
      "SE": { "type": ["number", "null", "string"] },
      "P-value": { "type": ["number", "null", "string"] },
      "Direction": { "type": ["string", "null"] },
      "direction": { "type": ["string", "null"] }
    },
    "required": [
      "exposure",
      "outcome",
      "beta",
      "units",
      "odds ratio",
      "hazard ratio",
      "95% CI",
      "SE",
      "P-value"
    ],
    "additionalProperties": false
  }
}

=== MRCIEU/llm-data-extraction/data/assets/data-schema/llama3/results.json
[
  {
    "exposure": "SGLT2 inhibition",
    "outcome": "Heart Failure (HF)",
    "beta": null,
    "units": null,
    "odds ratio": 0.44,
    "hazard ratio": null,
    "95% CI": [
      0.26,
      0.76
    ],
    "SE": null,
    "P-value": 0.003,
    "direction": "decreases"
  },
  {
    "exposure": "SGLT2 inhibition",
    "outcome": "LRRTM2",
    "beta": -0.2,
    "units": null,
    "odds ratio": null,
    "hazard ratio": null,
    "95% CI": [
      -0.39,
      -0.06
    ],
    "SE": null,
    "P-value": 0.02,
    "direction": "decreases"
  }
]
